apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  namespace: foodgram
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"
