apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: foodgram
spec:
  selector:
    app: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None   # Headless Service для StatefulSet
