apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ $.Values.global.namespace }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.service.ports.name }}
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
      protocol: {{ .Values.service.ports.protocol }}
  selector:
    app: {{ .Chart.Name }}
