apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.locust.name }}-locustfile
  namespace: {{ .Values.global.namespace }}
data:
  locustfile.py: |
{{ .Files.Get "files/locustfile.py" | indent 4 }}
