global:
  namespace: foodgram
  db:
    host: postgres-headless-svc.foodgram.svc.cluster.local
    port: 5432
  secret:
    db: db-secret
    rabbitmq: rabbit-secret
    redis: redis-secret
  config:
    db: db-configmap
    rabbitmq: rabbit-config
    redis: redis-configmap
  images: 
    api:
      name: udazzzz/foodgram_backend:latest
      pullPolicy: Always

backend:
  name: backend
  replicas: 2
  port: 8000
  mediaRoot: /app/media
  volumeMountPath: /app/media
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 700m
      memory: 512Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 0
        selectPolicy: Max
        policies:
          - type: Percent
            value: 100
            periodSeconds: 60
          - type: Pods
            value: 2
            periodSeconds: 60
      scaleDown:
        stabilizationWindowSeconds: 300
        selectPolicy: Min
        policies:
          - type: Percent
            value: 50
            periodSeconds: 60
  vpa:
    enabled: true
    updateMode: "Off"
    controlledResources:
      - memory
    minAllowed:
      memory: 256Mi
    maxAllowed:
      memory: 1Gi
  env:
    media_root: /app/media
    secret:
      db:
        POSTGRES_USER: POSTGRES_USER
        POSTGRES_PASSWORD: POSTGRES_PASSWORD
        POSTGRES_DB: POSTGRES_DB
      rabbitmq:
        BROKER_USER: username
        BROKER_PASSWORD: password
      redis:
        REDIS_PASSWORD: password
    config:
      db:
        DB_HOST: DB_HOST
        DB_PORT: DB_PORT
      rabbitmq:
        BROKER_HOST: host
        BROKER_PORT: port
      redis:
        APP_REDIS_HOST: host
        APP_REDIS_PORT: port

nginx:
  name: nginx
  image: udazzzz/foodgram_frontend:latest
  imagePullPolicy: IfNotPresent
  port: 80
  volumeMountPath: /app/media/

pvc:
  name: media-pvc
  accessModes:
    - ReadWriteMany
  storage: 5Gi

ingress:
  name: foodgram-ingress
  className: nginx
  host: foodgram.localhost.ru
  paths:
    - path: /api
      service: backend
      port: 8000
    - path: /admin
      service: backend
      port: 8000
    - path: /static
      service: nginx
      port: 80
    - path: /media
      service: nginx
      port: 80
    - path: /
      service: nginx
      port: 80

postgres:
  name: postgres
  statefulsetName: postgres-sts
  appLabel: postgres
  image: postgres:17
  imagePullPolicy: IfNotPresent
  replicas: 1
  storage: 10Gi
  dataPath: /var/lib/postgresql/data
  pgData: /var/lib/postgresql/data/pgdata
  headlessService:
    name: postgres-headless-svc
    clusterIP: None
  secret:
    username: ref+vault://secrets/db#/POSTGRES_USER
    password: ref+vault://secrets/db#/POSTGRES_PASSWORD
    database: ref+vault://secrets/db#/POSTGRES_DB

jobMigrate:
  name: backend-migrations
  command: ["python", "manage.py", "migrate", "--noinput"]
  restartPolicy: OnFailure

jobLoaddata:
  name: backend-loaddata
  command: ["python", "manage.py", "loaddata", "data/ingredients.json"]
  restartPolicy: OnFailure
