apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.global.config.db }}
data:
  DB_HOST: "{{ .Values.global.db.host }}"
  DB_PORT: "{{ .Values.global.db.port }}"
