apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ .Values.global.images.api.name }}
        imagePullPolicy: {{ .Values.global.images.api.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
          {{- $global := .Values.global }}
          {{- range $alias, $mapping := .Values.backend.env.secret }}
            {{- range $key, $val := $mapping }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ index $global.secret $alias }}
                key: {{ $val }}
            {{- end }}
          {{- end }}
          {{- range $alias, $mapping := .Values.backend.env.config }}
            {{- range $key, $val := $mapping }}
          - name: {{ $key }}
            valueFrom:
              configMapKeyRef:
                name: {{ index $global.config $alias }}
                key: {{ $val }}
            {{- end }}
          {{- end }}
          - name: MEDIA_ROOT
            value: "{{ .Values.backend.mediaRoot }}"
          - name: CELERY_BROKER_URL
            value: "amqp://admin:secretpassword@my-rabbitmq.foodgram.svc.cluster.local:5672//"

        volumeMounts:
        - name: media-files
          mountPath: {{ .Values.backend.volumeMountPath }}
        resources:
{{ toYaml .Values.backend.resources | indent 10 }}
      volumes:
      - name: media-files
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
