apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobLoaddata.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.global.images.api.name }}
          imagePullPolicy: {{ .Values.global.images.api.pullPolicy }}
          command: {{ toJson .Values.jobLoaddata.command }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.db }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.db }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.db }}
                  key: POSTGRES_DB
            - name: DB_HOST
              value: "{{ .Values.global.db.host }}"
            - name: DB_PORT
              value: "{{ .Values.global.db.port }}"
      restartPolicy: {{ .Values.jobLoaddata.restartPolicy }}
