apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobMigrate.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ .Values.global.images.api.name }}
        command: {{ toJson .Values.jobMigrate.command }}
        envFrom:
        - secretRef:
            name: {{ .Values.global.secret.db }}
        - configMapRef:
            name: {{ .Values.global.config.db }}
      restartPolicy: {{ .Values.jobMigrate.restartPolicy }}
