apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: "{{ .Values.postgres.secret.username | b64enc }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.secret.password | b64enc }}"
  POSTGRES_DB: "{{ .Values.postgres.secret.database | b64enc }}"
