apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.headlessService.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  clusterIP: {{ .Values.postgres.headlessService.clusterIP }}
  ports:
    - name: postgresql
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
  selector:
    app: {{ .Values.postgres.appLabel }}
