apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrations
  namespace: foodgram
spec:
  template:
    spec:
      containers:
      - name: backend
        image: udazzzz/foodgram_backend:latest
        command: ["python", "manage.py", "migrate", "--noinput"]
        envFrom:
        - secretRef:
            name: db-secret
        - configMapRef:
            name: db-configmap
      restartPolicy: OnFailure
