apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: foodgram
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;

        location /api/ {
          proxy_pass http://backend.foodgram.svc.cluster.local:8000/api/;
          proxy_set_header Host $http_host;
        }

        location /admin/ {
          proxy_pass http://backend.foodgram.svc.cluster.local:8000/admin/;
          proxy_set_header Host $http_host;
        }

        location /api/docs/ {
          root /usr/share/nginx/html;
          try_files $uri $uri/redoc.html;
        }

        location /static/ {
          alias /usr/share/nginx/html/static/;
        }

        location /media/ {
          alias /var/html/media/;
        }

        location /static/admin/ {
          alias /app/static/admin/;
        }
        
        location / {
          root /usr/share/nginx/html/;
          index index.html index.htm;
          try_files $uri /index.html;
        }
      }
    }