apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: foodgram
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: foodgram-nginx:latest   # твой собранный образ
        ports:
        - containerPort: 80
        volumeMounts:
        - name: media-files
          mountPath: /var/html/media/
      volumes:
      - name: media-files
        persistentVolumeClaim:
          claimName: media-pvc
