apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: foodgram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.4-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
