name: Main Foodgram Workflow

on:
    push:
        branches:
            - main

jobs:
    checkout-code-pep8:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:15
                ports:
                    - 5432:5432
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip 
                  pip install ruff==0.8.0
                  pip install -r backend/requirements.txt
                  pip install pytest pytest-django psycopg2-binary
            - name: Tests
              env:
                  DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
                  DB_ENGINE: django.db.backends.postgresqlAdd commentMore actions
                  DB_NAME: test
                  POSTGRES_DB: test
                  DB_USER: postgres
                  POSTGRES_USER: postgres
                  DB_PASSWORD: postgres
                  POSTGRES_PASSWORD: postgres
                  DB_HOST: localhost
                  DB_PORT: 5432
              run: |
                  python -m ruff check backend/
                  python backend/manage.py migrate
                  pytest backend/tests/

    build_and_push_to_docker_hub:
        name: Push Docker image to DockerHub
        runs-on: ubuntu-latest
        needs: checkout-code-pep8
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push to DockerHub
              uses: docker/build-push-action@v5
              with:
                  context: ./backend/
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/foodgram:latest

    build_frontend_and_push_to_docker_hub:
        name: Push frontend Docker image to DockerHub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push to DockerHub
              uses: docker/build-push-action@v5
              with:
                  context: ./frontend/
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest
