apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.global.secret.rabbitmq }}
  namespace: {{ $.Values.global.namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
